name: BlightedSMP
version: '${version}'
authors: [ MrInspection ]

main: fr.moussax.blightedSMP.BlightedSMP
api-version: '26.3'
load: STARTUP

commands:
  spawncustommob:
    description: Spawn a BlightedMC creature
    aliases:
      - scm
  test:
    description: General testing command
  blight:
    description: Manage the Blight currency system
    aliases:
      - b
  craft:
    description: Open the BlightedMC custom crafting table
  loop:
    description: Bulk execute a specific command
  giveitem:
    description: Open or give yourself a custom item
  tppos:
    description: Teleport to a position
  forge:
  altar:
  gms:
    description: Switch to survival mode
  gmc:
    description: Switch to creative mode
  gmspec:
    description: Switch to spectator mode
  gma:
    description: Switch to adventure mode
  nightvision:
    description: Toggle night vision for yourself
    aliases:
      - nv
  god:
  butcher:
  speed:
  fly: